### ISSUE TITLE
experiment configuration

### ISSUE THREAD

**Issue by wsj-blip** [summitgao/WBANet#2]
1、Could you please tell me which part of the code corresponds to the number of Wavelet-based Bi-dimensional Aggregation Blocks in the experimental setup?
2、if im1_path == '/content/Yellow_River_1.bmp':
  im1 = io.imread(im1_path).astype(np.float32)
  im2 = io.imread(im2_path).astype(np.float32)
  im_gt = io.imread(imgt_path).astype(np.float32)
Does the image file corresponding to the first line of code need to be replaced with “_gt.bmp”?

**Comment by summitgao** [comment]
没太明白你的意思，欢迎邮件联系， gaofeng@ouc.edu.cn
